"""Add selection basket fields

Revision ID: 218d321310dd
Revises: 0009_batch_fields
Create Date: 2025-09-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

revision = '218d321310dd'
down_revision = '0009_batch_fields'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_state', sa.Column('selected_artifact_ids', sa.Text(), nullable=True))
    op.add_column('user_state', sa.Column('auto_clear_selection', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('user_state', sa.Column('last_batch_tag', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_state', 'last_batch_tag')
    op.drop_column('user_state', 'auto_clear_selection')
    op.drop_column('user_state', 'selected_artifact_ids')
    # ### end Alembic commands ###