services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 20
    # Внешний порт БД не публикуем — боту он не нужен
    ports:
      - "5432:5432"
    volumes:
      - linkbot_db_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    # Порты для доступа с хоста (консоль/UI)
    ports:
      - "9100:9000"
      - "9101:9001"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:9000/minio/health/ready || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    volumes:
      - linkbot_minio_data:/data

  bot:
    build: .
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy   # ждем именно готовности MinIO
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATABASE_URL=postgresql+asyncpg://memuser:secret@db:5432/memdb
      - PROJECT_MAX_CHUNKS=${PROJECT_MAX_CHUNKS}
      - CHUNK_SIZE=${CHUNK_SIZE}
      - CHUNK_OVERLAP=${CHUNK_OVERLAP}
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET=${MINIO_BUCKET}
      - MINIO_SECURE=${MINIO_SECURE}
      - LLM_DISABLED=${LLM_DISABLED}
      - LLM_MODEL=${LLM_MODEL}
      - LLM_TIMEOUT=${LLM_TIMEOUT}
      - LLM_MAX_TOKENS_OUT=${LLM_MAX_TOKENS_OUT}
      - LLM_TEMPERATURE=${LLM_TEMPERATURE}
      - DOCKER_ENV=true
    volumes:
      - ./:/app
      - repos_data:/app/repos   # локальный кэш git
    command: ["sh","-c","alembic upgrade head && python -m app.main"]  # Run migrations before starting the bot

volumes:
  linkbot_db_data:
  linkbot_minio_data:
  repos_data: